### ISSUE TITLE
Unhandled error clauses

### ISSUE THREAD

**Issue by Chatatata** [Chatatata/iyzico#11]
Following clause is not handled, exception is raised instead.

    ** (exit) an exception was raised:
       ** (Iyzico.InternalInconsistencyError) Unexpected error.
           lib/endpoint/bin_inquiry.ex:172: Iyzico.BinInquiry.handle_error/1
           (buy_buddy) lib/buy_buddy/payment/iyzico.ex:195: BuyBuddy.Payment.Iyzico.card_info/3
           (buy_buddy) src/orders/overview/card_info_controller.ex:119: BuyBuddy.Orders.Overview.CardInfoController.show/2
           (buy_buddy) src/orders/overview/card_info_controller.ex:1: BuyBuddy.Orders.Overview.CardInfoController.action/2
           (buy_buddy) src/orders/overview/card_info_controller.ex:1: BuyBuddy.Orders.Overview.CardInfoController.phoenix_controller_pipeline/2
           (buy_buddy) lib/buy_buddy/endpoint.ex:1: BuyBuddy.Endpoint.instrument/4
           (buy_buddy) lib/phoenix/router.ex:261: BuyBuddy.Router.dispatch/2
           (buy_buddy) src/router.ex:1: BuyBuddy.Router.do_call/2

**Comment by Chatatata** [comment]
@encku
